import MainNavbar from "../../components/Navbars/MainNavbar"

export const metadata = {
  title: 'MediFind Authentication',
  description: 'Generated by Next.js',
}

export default function RootLayout({  children,}: {children: React.ReactNode}) {
  return (
    <div>
        <MainNavbar/>
        {children} 
    </div>
  )
}
