import './globals.css'
import { Providers } from './providers'


export const metadata = {
  title: 'MediFind',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='dark:bg-myBlack-900'>
          <Providers>{children}</Providers>
      </body>
    </html>
  )
}
